### ISSUE TITLE
Remove whipper's retag feature

### ISSUE THREAD

**Issue by mtdcr** [JoeLametta/whipper#262]
```
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/dist-packages/whipper/command/main.py", line 40, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/image.py", line 97, in do
    t = encode.SafeRetagTask(path, taglist)
AttributeError: 'module' object has no attribute 'SafeRetagTask'
```

SafeRetagTask was removed in e7767694af535e68e3eaff01b474dd4371e2d3e5 („Rip out all code that directly uses gstreamer“).

Command to reproduce: `whipper image retag *.cue`

**Comment by JoeLametta** [comment]
Hi, this is a known issue.

> The image retag feature has been knowingly broken since PR #130.

For more information please read [this comment](https://github.com/JoeLametta/whipper/issues/29#issuecomment-277182980) and check [whipper's v0.5.0 release notes](https://github.com/JoeLametta/whipper/releases/tag/v0.5.0). It's very likely that this feature will be completely removed in whipper's next release.

Cheers,
Joe
